### ISSUE TITLE
[Isuues][Modulo Roles] Ordenas datos en la hoja de reportes de roles

### ISSUE THREAD

**Issue by Conradov1534** [CesarChambi2002/Proyecto-3-Sis.Administracion#9]
En los datos de la hoja del modulo de roles se muestra la acción de editar

1. Seleccionar el modulo Roles
2. Seleccionar la opción listado de roles
3. Hacer click en el botón "Reportes" y seleccionar la opción PDF
Se descargara un PDF con todos los datos de roles.
![imagen (1)](https://github.com/user-attachments/assets/3d264252-9df0-46fb-847a-6945360f7c60)

**Comment by CesarChambi2002** [comment]
Terminado Se ordenaron los datos de la hoja.
